Круглов В.
java-park-mail-ru/rk2_cases pull request #1
Opened 2017-05-03 14:39 UTC by yaches

2017-05-03 22:01 UTC, KSolovyev requested changes

2017-05-03 22:01 UTC, KSolovyev commented on exploders/src/SchedulerService.java
> +        SortedMap<Long, Job> jobsToExecute = awaitingJobs.subMap((long) 0, currentTime);
`0L` можно писать

2017-05-03 22:01 UTC, KSolovyev commented on exploders/src/SchedulerService.java
>          }
можно сделать что-то типа `awaitingJobs = awaitingJobs.headMap(currentTime)`  будет быстрее, но надо поменять код не в тех местах, где я отметил

2017-05-09 10:33 UTC, KSolovyev commented
@yaches ?

2017-05-09 11:06 UTC, yaches commented
Простите, дел много. Исправлю в ближайшем времени)

2017-05-15 14:07 UTC, KSolovyev commented
ок

2017-05-15 14:07 UTC, closed without merging