Буклин С.
java-park-mail-ru/rk2_cases pull request #2
Opened 2017-05-06 11:51 UTC by XfortunaX

2017-05-06 11:56 UTC, KSolovyev requested changes

2017-05-06 11:56 UTC, KSolovyev commented on exploders/src/SchedulerService.java
> +            if (longJobEntry.getKey() <= (currentTime + frameMillis)) {
неверно, тут ы возьмете задачи из будущего

2017-05-06 11:56 UTC, KSolovyev commented on exploders/src/Bomb.java
> -}
а зачем последнюю пустую строку поудаляли?

2017-05-06 12:12 UTC, XfortunaX commented on exploders/src/SchedulerService.java
> +            if (longJobEntry.getKey() <= (currentTime + frameMillis)) {
Чтобы не пропустить задачи, из предположения что следующий frametime будет такой же, взрываю бомбы раньше)

2017-05-06 12:12 UTC, XfortunaX commented on exploders/src/Bomb.java
> -}
случайно)

2017-05-06 23:13 UTC, KSolovyev commented on exploders/src/SchedulerService.java
> +            if (longJobEntry.getKey() <= (currentTime + frameMillis)) {
я неправильно отписался. Здесь проверка вообще не нужна. Как думаете, почему?

2017-05-09 10:32 UTC, KSolovyev commented
@XfortunaX ?

2017-05-15 14:07 UTC, closed without merging